__title__ = 'flake8-junit-report'
__summary__ = 'Simple tool that converts a flake8 file to junit format'
__version__ = '0.1.2'
__license__ = 'BSD 3-Clause License'
__uri__ = 'https://github.com/initios/flake8-junit-report'
__author__ = 'Carlos Goce'
__email__ = 'carlosgoce@gmail.com'
